name: Send Interview Reminders

on:
  schedule:
    - cron: '*/30 * * * *' # Every 30 minutes
  workflow_dispatch: # Manual trigger option

jobs:
  run-reminder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set environment variables
      run: |
        echo "NOTION_TOKEN=${{ secrets.NOTION_TOKEN }}" >> $GITHUB_ENV
        echo "DATABASE_ID=${{ secrets.DATABASE_ID }}" >> $GITHUB_ENV

    - name: Write Gmail token to token.json
      run: echo '${{ secrets.GOOGLE_TOKEN }}' > token.json

    - name: Validate token.json
      run: jq . token.json

    - name: Run the reminder sender
      run: python reminder_sender.py
