name: Run Interview Reminder Script

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'  # every 30 mins for example

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
  - name: Checkout code
    uses: actions/checkout@v3

  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.10'

  - name: Install dependencies
    run: pip install -r requirements.txt

  - name: Create credentials.json from secret
    run: echo "$GOOGLE_CREDENTIALS" > credentials.json
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

  - name: Create token.json from secret
    run: echo "$GOOGLE_TOKEN" > token.json
    env:
      GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}

  - name: Run Reminder Script
    run: python reminder_sender.py
    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      DATABASE_ID: ${{ secrets.DATABASE_ID }}
